# Generated by Django 2.0 on 2019-05-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190503_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='preference',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='base_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='headline',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='product',
            name='preference',
            field=models.CharField(choices=[('EX', 'Excellent'), ('VG', 'Very Good'), ('GD', 'Good'), ('AV', 'Average')], max_length=2),
        ),
    ]
