# Generated by Django 2.0 on 2019-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190503_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preference',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Excellent'), (2, 'Very Good'), (3, 'Good'), (4, 'Average')], default=2),
        ),
    ]
