# Generated by Django 2.0 on 2019-05-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190503_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_pieces',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
