# Generated by Django 2.0 on 2019-05-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190505_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_man',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='singleproductorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='DeliveryMan',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='SingleProductOrder',
        ),
    ]
