# Generated by Django 2.0 on 2019-05-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20190516_0209'),
        ('portal', '0009_auto_20190508_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='PhotoPosition',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
