# Generated by Django 2.0 on 2019-05-18 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=264)),
                ('address_line_2', models.CharField(max_length=264)),
                ('address_line_3', models.CharField(max_length=264)),
                ('address_type', models.CharField(default='Home', max_length=32)),
                ('contact_no', models.CharField(max_length=13)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('coordinates', models.CharField(blank=True, max_length=256)),
                ('delivery_charges', models.DecimalField(decimal_places=2, max_digits=7)),
                ('city', models.CharField(default='Pune', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Locality'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
