# Generated by Django 2.0 on 2019-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190519_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='session_key',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
