# Generated by Django 2.0 on 2019-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20190521_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line_3',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address_line_1',
            field=models.CharField(max_length=264, verbose_name='Flat or builiding name'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address_line_2',
            field=models.CharField(max_length=264, verbose_name='Street Name'),
        ),
    ]
