# Generated by Django 2.0 on 2019-05-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20190508_1234'),
        ('carts', '0003_auto_20190508_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line_1', models.CharField(max_length=264)),
                ('address_line_2', models.CharField(max_length=264)),
                ('address_line_3', models.CharField(max_length=264)),
                ('address_type', models.CharField(default='Home', max_length=32)),
                ('city', models.CharField(default='Pune', max_length=32)),
                ('contact_no', models.CharField(max_length=13)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(default='COD', max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_before', models.DateField()),
                ('deliverd_on', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productentry',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='productentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.DeliveryAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.DeliveryMan'),
        ),
    ]
