# Generated by Django 2.0 on 2019-05-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190516_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Product'),
        ),
    ]
