# Generated by Django 2.0 on 2019-05-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190525_0135'),
        ('carts', '0013_auto_20190521_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
            preserve_default=False,
        ),
    ]
