# Generated by Django 2.0 on 2019-05-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0005_auto_20190516_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line_1', models.CharField(max_length=264)),
                ('address_line_2', models.CharField(max_length=264)),
                ('address_line_3', models.CharField(max_length=264)),
                ('address_type', models.CharField(default='Home', max_length=32)),
                ('city', models.CharField(default='Pune', max_length=32)),
                ('contact_no', models.CharField(max_length=13)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(default='COD', max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_before', models.DateField()),
                ('deliverd_on', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='carts.Cart')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.DeliveryAddress')),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.DeliveryMan')),
            ],
        ),
    ]
