# Generated by Django 2.0 on 2019-05-16 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190517_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_before',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 21, 30, 34, 839389, tzinfo=utc)),
        ),
    ]
