# Generated by Django 2.0 on 2019-05-16 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190517_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_before',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 22, 39, 25, 400006, tzinfo=utc)),
        ),
    ]
