# Generated by Django 2.0 on 2019-05-18 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190519_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_before',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 20, 19, 6, 765881, tzinfo=utc)),
        ),
    ]
