# Generated by Django 2.2.1 on 2019-05-21 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190519_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_before',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 9, 13, 0, 481482, tzinfo=utc)),
        ),
    ]
