# Generated by Django 2.0 on 2019-05-21 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190521_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_before',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 10, 30, 22, 787961, tzinfo=utc)),
        ),
    ]
