# Generated by Django 2.0 on 2019-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbrevation', models.CharField(max_length=8)),
                ('hex_code', models.CharField(default='#FF0000', max_length=7)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbrevation', models.CharField(max_length=8)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('headline', models.CharField(max_length=48)),
                ('details', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preference', models.PositiveSmallIntegerField(choices=[(1, 'Excellent'), (2, 'Very Good'), (3, 'Good'), (4, 'Average')], default=2)),
                ('tag', models.CharField(blank=True, max_length=5)),
                ('available_pieces', models.PositiveSmallIntegerField(default=100)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='products.Category')),
                ('colors', models.ManyToManyField(to='products.Color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/product_photos/')),
                ('base_photo', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Color')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.PhotoPosition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbrevation', models.CharField(max_length=8)),
                ('length', models.CharField(max_length=16)),
                ('unit', models.CharField(max_length=16)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='products.Size'),
        ),
    ]
