# Generated by Django 2.0 on 2019-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_current_ocassion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='unit',
            field=models.CharField(default='Inch', max_length=16),
        ),
    ]
